### ISSUE TITLE
docs-cloud-servers General API section AWOL

### ISSUE THREAD

**Issue by ktbartholomew** [rackerlabs/docs-cloud-servers#129]
Moved from https://github.com/deconst/deconst-docs/issues/221.

> If i build my servers doc locally, the general API section shows up in singlebuild html file. It is AWOL from the published doc however. (Local deconst client is broken, so i can’t test that). How do we get all sections to publish in production, please?

/cc @catlook @smashwilson @meker12

**Comment by catlook** [comment]
the extension section also missing.

**Comment by smashwilson** [comment]
It's certainly [being built](https://travis-ci.org/rackerlabs/docs-cloud-servers#L181) and the [content IDs](https://github.com/rackerlabs/nexus-control/blob/master/config/content.d/developer.rackspace.com.json#L26) [match](https://github.com/rackerlabs/docs-cloud-servers/blob/master/api-docs/_deconst.json#L2).

**Comment by ktbartholomew** [comment]
@catlook since this repo uses the single page builder, missing content would indicate that the Sphinx markup isn't formatted quite right, and thus portions of the doc just aren't being submitted.

**Comment by catlook** [comment]
Local sphinx build works just fine.  Why would it be different for the production build?  Is there a file I need to update somewhere?

-- Cat Lookabaugh, Sr. Information Developer
Rackspace Hosting – the #1 Managed Cloud Company
DevDocs on Developer Experience Team
Office: (210) 312-8193   Cell: (210) 364-1060
cat.lookabaugh@rackspace.com

We should not write so that it is possible for the reader to understand us, but so that it is impossible for him to misunderstand us. - Quintilian, rhetorician (c. 35-100)

Harmony + Learner + Responsibility + Context + Intellection + Arranger + Consistency + Relator + Input + Analytical

**Comment by ktbartholomew** [comment]
The affected sections are having the CSS classes added to make them collapsible sections, but they're nested inside another collapsible section (which is a no-no), so they're not appearing (visually) at all. The content is there, though, so Sphinx and deconst are both off the hook.

**Comment by ktbartholomew** [comment]
Issue _avoided_ w/ https://github.com/rackerlabs/nexus-control/pull/341
