### ISSUE TITLE
Missing server prices

### ISSUE THREAD

**Issue by hkmaly** [rackerlabs/docs-cloud-servers#186]
Hello,

not sure if it's missing from documentation or from API, but would it be possible to get the expected monthly price for given flavor (the same number displayed when I'm creating the server directly on rackspace cloud control center)?

**Comment by catlook** [comment]
Hkmaly,

Hi, over the last year we've done a complete revamp and refresh of our API documentation.  We found a bunch of out-of-date information, like pricing and SLAs, that are maintained elsewhere, so we pulled them from the API docs. Here are some links where you can find the most current details:
https://www.rackspace.com/openstack/public/pricing
https://www.rackspace.com/managed-hosting/service-levels

Since the price of a server depends on both image and flavor, an easy way to determine the exact price is to go the your Cloud Control Panel, choose Servers, and then Create a server.  Select the image and flavor, and the price is displayed in the upper right corner of the window.  I hope this helps!

**Comment by hkmaly** [comment]
... I meant to get the price from the API itself, so I can display list of flavors with (current) price.

But considering I already got answer that it is not and wouldn't be in the API anytime soon on https://community.rackspace.com/developers/f/7/p/8011/13846 then the problem is not in the documentation.

**Comment by catlook** [comment]
Thanks for clarifying!!

-- Cat Lookabaugh, Sr. Information Developer
Rackspace Hosting – the #1 Managed Cloud Company
Info Dev Team      cat.lookabaugh@rackspace.com
Office: (210) 312-8193   Cell: (210) 364-1060
