### ISSUE TITLE
Rescue Mode should include custom image option

### ISSUE THREAD

**Issue by thinmintaddict** [rackerlabs/docs-cloud-servers#25]
Recently the option was added to rescue a cloud server from a different image than the base_image_ref in NovaDB. To do so, you just add the rescue image uuid like this:

'{"rescue": {"rescue_image_ref": "'"$RESCIMG"'"}}'

A full curl call as we typically execute it:

##Bash Variables needed 
TOKEN= API Token, customer or impersonation 
RGN=region, dfw, ord, etc..
DDI=Customer DDI 
INSTANCE=Instance_UUID 
RESCIMG=Rescue_Image_UUID

##Curl command to place instance in to recue mode with specified image 
curl -X POST -H "X-Auth-Token: $TOKEN" https://$RGN.servers.api.rackspacecloud.com/v2/$DDI/servers/$INSTANCE/action -d '{"rescue": {"rescue_image_ref": "'"$RESCIMG"'"}}' -H "Content-type: application/json” | python -m json.tool

Can we get the "rescue_image_ref" variable added to the documentations?

As a side note, I would love to sit down and discuss how this project is formatted so that I can submit pull requests rather than issues.

Thanks!

Russell

**Comment by catlook** [comment]
Russell,

Thanks for the heads up!  I'll work on getting this info incorporated into the current docs.  I'll ping you if I have any questions!

As for your other question, we are currently converting docs from the docbook format to RST format.  In a couple of months you'll absolutely be able (and encouraged) to do pull requests to keep our docs current, correct, and relevant!!!

-- Cat Lookabaugh, Sr. Information Developer
Rackspace Hosting - the #1 Managed Cloud Company
DevDocs on Developer Experience Team
Office: (210) 312-8193   Cell: (210) 364-1060
cat.lookabaugh@rackspace.com

We should not write so that it is possible for the reader to understand us, but so that it is impossible for him to misunderstand us. - Quintilian, rhetorician (c. 35-100)

Harmony + Learner + Responsibility + Context + Intellection + Arranger + Consistency + Relator + Input + Analytical

**Comment by catlook** [comment]
done
